import express from "express";
import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

const app = express();
app.use(express.json());

// API route for sending reports
app.post("/api/send-report", async (req, res) => {
  const { email, report, lang } = req.body;

  if (!email || !report) {
    return res.status(400).json({ error: "Missing email or report data" });
  }

  try {
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const subject = lang === 'mr' 
      ? `तुमचा मासिक आर्थिक अहवाल - ${report.month}`
      : `Your Monthly Financial Report - ${report.month}`;

    const mailOptions = {
      from: `"Family Finance Manager" <${process.env.SMTP_USER}>`,
      to: email,
      subject: subject,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 12px;">
          <h2 style="color: #ea580c; margin-bottom: 20px;">${subject}</h2>
          
          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <p style="margin: 0; font-size: 14px; color: #6b7280;">${lang === 'mr' ? 'एकूण उत्पन्न' : 'Total Income'}</p>
            <p style="margin: 0; font-size: 24px; font-weight: bold; color: #16a34a;">₹${report.totalIncome.toLocaleString()}</p>
          </div>

          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <p style="margin: 0; font-size: 14px; color: #6b7280;">${lang === 'mr' ? 'एकूण खर्च' : 'Total Expense'}</p>
            <p style="margin: 0; font-size: 24px; font-weight: bold; color: #dc2626;">₹${report.totalExpense.toLocaleString()}</p>
          </div>

          <div style="background: #ea580c; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <p style="margin: 0; font-size: 14px; opacity: 0.8;">${lang === 'mr' ? 'शिल्लक' : 'Balance'}</p>
            <p style="margin: 0; font-size: 24px; font-weight: bold;">₹${report.balance.toLocaleString()}</p>
          </div>

          <h3 style="border-bottom: 1px solid #e5e7eb; padding-bottom: 10px;">${lang === 'mr' ? 'वर्गानुसार खर्च' : 'Category Breakdown'}</h3>
          <ul style="list-style: none; padding: 0;">
            ${Object.entries(report.categoryBreakdown).map(([cat, amt]) => `
              <li style="display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6;">
                <span>${cat}</span>
                <span style="font-weight: bold;">₹${amt.toLocaleString()}</span>
              </li>
            `).join('')}
          </ul>

          <h3 style="border-bottom: 1px solid #e5e7eb; padding-bottom: 10px; margin-top: 20px;">${lang === 'mr' ? 'कर्ज सारांश' : 'Loan Summary'}</h3>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
            <p><strong>${lang === 'mr' ? 'दिलेले' : 'Lent'}:</strong> ₹${report.loanSummary.lent.toLocaleString()}</p>
            <p><strong>${lang === 'mr' ? 'घेतलेले' : 'Borrowed'}:</strong> ₹${report.loanSummary.borrowed.toLocaleString()}</p>
            <p><strong>${lang === 'mr' ? 'परत आलेले' : 'Returned'}:</strong> ₹${report.loanSummary.returned.toLocaleString()}</p>
            <p><strong>${lang === 'mr' ? 'प्रलंबित' : 'Pending'}:</strong> ₹${report.loanSummary.pending.toLocaleString()}</p>
          </div>

          <p style="margin-top: 30px; font-size: 12px; color: #9ca3af; text-align: center;">
            ${lang === 'mr' ? 'कुटुंब अर्थ व्यवस्थापक द्वारे स्वयंचलितपणे व्युत्पन्न' : 'Automatically generated by Family Finance Manager'}
          </p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);
    res.json({ success: true });
  } catch (error) {
    console.error("Email error:", error);
    res.status(500).json({ error: "Failed to send email" });
  }
});

export default app;
